### ISSUE TITLE
关于GHOF_Clean.npy和GHOF_Final.npy

### ISSUE THREAD

**Issue by ZhengFengkai87** [MegEngine/GyroFlow#3]
您好，您提供的GHOF_Clean.npy和GHOF_Final.npy下载链接失效了，可以重新分享一下吗？谢谢！

**Comment by lhaippp** [comment]
hi, sry for the late respond. you can check the dataset in this link: https://github.com/lhaippp/GyroFlowPlus

**Comment by ZhengFengkai87** [comment]
Many thanks for sharing!



---原始邮件---
发件人: "Li ***@***.***&gt;
发送时间: 2023年10月14日(周六) 晚上9:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MegEngine/GyroFlow] 关于GHOF_Clean.npy和GHOF_Final.npy (Issue #3)




 
hi, sry for the late respond. you can check the dataset in this link: https://github.com/lhaippp/GyroFlowPlus
